// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDghgthKnmZguRk3BBtUbniHJ1rIsO3TSM',
    appId: '1:333482905391:web:afde233e1b4314efb25bda',
    messagingSenderId: '333482905391',
    projectId: 'cginot-mobile-app',
    authDomain: 'cginot-mobile-app.firebaseapp.com',
    storageBucket: 'cginot-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxK7lBij1ETnPXu4S-TqwOS_MuIDi3azc',
    appId: '1:333482905391:android:7a0b4225c8aeb5eeb25bda',
    messagingSenderId: '333482905391',
    projectId: 'cginot-mobile-app',
    storageBucket: 'cginot-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPgGHBR2QgRg9OSUE5O7bYjcq7YJQ_SpE',
    appId: '1:333482905391:ios:6f6930e03de1ee47b25bda',
    messagingSenderId: '333482905391',
    projectId: 'cginot-mobile-app',
    storageBucket: 'cginot-mobile-app.appspot.com',
    androidClientId: '333482905391-71uq5ds3bqbqesvs12fgrs6kkjfgbuf8.apps.googleusercontent.com',
    iosClientId: '333482905391-o9mnqqeu7gmr4qngj620mbureeu5j910.apps.googleusercontent.com',
    iosBundleId: 'com.example.cginotApp',
  );
}
